# Generated by Django 4.2 on 2023-05-01 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.company')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(max_length=20)),
                ('container_type', models.CharField(max_length=10)),
                ('tare_weight', models.FloatField()),
                ('on_port', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_per_tonnage', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imo_number', models.CharField(max_length=15)),
                ('flag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voyage_number', models.CharField(max_length=50)),
                ('from_port', models.CharField(max_length=200)),
                ('to_port', models.CharField(max_length=200)),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('voyage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='operations.voyage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.company')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.servicetype')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.vessel')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='PortHandling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateTimeField()),
                ('departure_date', models.DateTimeField()),
                ('port', models.CharField(max_length=200)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.cargo')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='looseCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.consignee')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.shipper')),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='consignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.consignee'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.container'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='shipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.shipper'),
        ),
        migrations.CreateModel(
            name='BillOfLading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_of_lading_number', models.CharField(max_length=50)),
                ('issued_date', models.DateTimeField()),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.cargo')),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.consignee')),
                ('loose_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.loosecargo')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.shipper')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.voyage')),
            ],
        ),
    ]
