# Generated by Django 4.2 on 2023-05-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.ManyToManyField(to='operations.servicetype'),
        ),
    ]
