# Generated by Django 4.2 on 2023-05-01 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='on_port',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.container'),
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voyage_number', models.CharField(max_length=50)),
                ('from_port', models.CharField(max_length=200)),
                ('to_port', models.CharField(max_length=200)),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='looseCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.consignee')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.shipper')),
            ],
        ),
        migrations.CreateModel(
            name='BillOfLading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_of_lading_number', models.CharField(max_length=50)),
                ('issued_date', models.DateTimeField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.cargo')),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.consignee')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.shipper')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.voyage')),
            ],
        ),
    ]
